[build]
target = "wasm32-unknown-unknown"
rustflags = [
    # The auto splitting runtime supports all the following WASM features.
    "-C", "target-feature=+bulk-memory,+mutable-globals,+nontrapping-fptoint,+sign-ext,+simd128",
]
target-dir = "target"

[alias]
# Alias for building an optimized version of the auto splitter.
# Command: cargo b
b = [
    "build", "--release",
]
d = [
    "build", "--release", "--config", "build.rustflags=[\"--cfg=debugger\"]",
]
